### ISSUE TITLE
Doesn't work on notion.so/guides/*

### ISSUE THREAD

**Issue by tddschn** [creold/open-in-notion#3]
When the extension is enabled, visiting https://www.notion.so/guides/timeline-view-unlocks-high-output-planning-for-your-team causes the tab to open itself repeatedly unless all tabs of the same URL is closed.

System info:
- OS: macOS 11.1
- Chrome: 87.0.4280.88
- Extension: 0.1.4

**Comment by creold** [comment]
Hi, Ted. I understand what's going on. I'll fix it

**Comment by creold** [comment]
Published in Webstore version 0.1.4.1. The problem was that for the extension, links to reserved pages of the Notion website were equivalent to links to users notes. For example https://www.notion.so/guides. I removed all such pages from the redirect, because the desktop application will not be able to open them =)

**Comment by tddschn** [comment]
Thank you for the fix! :)
