### ISSUE TITLE
Force new notion window on desktop when opening

### ISSUE THREAD

**Issue by jondkinney** [creold/open-in-notion#4]
I'd prefer a setting to enable Notion desktop to always open each link in a new window. I frequently have 3-4-5 Notion windows open tracking various things throughout the day (projects, articles, tasks, team members, etc.) and when I click a link and it opens in the desktop I lose whatever I was working on in the foreground Notion window.

**Comment by creold** [comment]
Hi, @jondkinney. I understand your wish. But I don't see a way to control the Notion app from Chrome so that it opens every link in a new window.

It seems that in your situation, you have to first open a new window in the Notion app (macOS → Shift + Cmd + N and Windows → Shift + Ctrl + N). And then open the link, so that the Chrome extension opens it in this window and not close all the others.
